[package]
name = "vdso_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
xmas-elf = "0.9.0"
lazy_init = { git = "https://github.com/Starry-OS/lazy_init.git" }
vdso = { path = "..", optional = true }
log = "0.4"

[features]
kernel = ["vdso"]